
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author soume
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    int turn=2;
    int btnused[]={0,0,0,0,0,0,0,0,0};
    int pXwon[]={0,0,0,0,0,0,0,0,0};
    int pOwon[]={0,0,0,0,0,0,0,0,0};
    
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
    LocalDateTime now = LocalDateTime.now();  
    //System.out.println(dtf.format(now));  
    
    

   
    int pXwon()
    {
        if(pXwon[0]==1&&pXwon[1]==1&&pXwon[2]==1)
            return 1;
        if(pXwon[3]==1&&pXwon[4]==1&&pXwon[5]==1)
            return 1;
        if(pXwon[6]==1&&pXwon[7]==1&&pXwon[8]==1)
            return 1;
        if(pXwon[0]==1&&pXwon[3]==1&&pXwon[6]==1)
            return 1;
        if(pXwon[0]==1&&pXwon[1]==1&&pXwon[2]==1)
            return 1;
        if(pXwon[1]==1&&pXwon[4]==1&&pXwon[7]==1)
            return 1;
        if(pXwon[2]==1&&pXwon[5]==1&&pXwon[8]==1)
            return 1;
        if(pXwon[0]==1&&pXwon[4]==1&&pXwon[8]==1)
            return 1;
        if(pXwon[2]==1&&pXwon[4]==1&&pXwon[6]==1)
            return 1;
        
        return 0;
    }
    
    int pOwon()
    {
        if(pOwon[0]==1&&pOwon[1]==1&&pOwon[2]==1)
            return 1;
        if(pOwon[3]==1&&pOwon[4]==1&&pOwon[5]==1)
            return 1;
        if(pOwon[6]==1&&pOwon[7]==1&&pOwon[8]==1)
            return 1;
        if(pOwon[0]==1&&pOwon[3]==1&&pOwon[6]==1)
            return 1;
        if(pOwon[0]==1&&pOwon[1]==1&&pOwon[2]==1)
            return 1;
        if(pOwon[1]==1&&pOwon[4]==1&&pOwon[7]==1)
            return 1;
        if(pOwon[2]==1&&pOwon[5]==1&&pOwon[8]==1)
            return 1;
        if(pOwon[0]==1&&pOwon[4]==1&&pOwon[8]==1)   
            return 1;
        if(pOwon[2]==1&&pOwon[4]==1&&pOwon[6]==1)
            return 1;
        
        return 0;
    }
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tic Tac Toe");

        jButton11.setText("RESET");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("MENU");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
         if(btnused[1]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn1.setText("X");
                btnused[1]=1;
                pXwon[1]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn1.setText("O");
                btnused[1]=1;
                pOwon[1]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
         if(btnused[2]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn2.setText("X");
                btnused[2]=1;
                pXwon[2]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn2.setText("O");
                btnused[2]=1;
                pOwon[2]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
         
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
         if(btnused[3]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn3.setText("X");
                btnused[3]=1;
                pXwon[3]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn3.setText("O");
                btnused[3]=1;
                pOwon[3]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if(btnused[0]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn0.setText("X");
                btnused[0]=1;
                pXwon[0]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                  
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn0.setText("O");
                btnused[0]=1;
                pOwon[0]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
         if(btnused[7]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn7.setText("X");
                btnused[7]=1;
                pXwon[7]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn7.setText("O");
                btnused[7]=1;
                pOwon[7]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
         if(btnused[4]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn4.setText("X");
                btnused[4]=1;
                pXwon[4]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn4.setText("O");
                btnused[4]=1;
                pOwon[4]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
         if(btnused[5]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn5.setText("X");
                btnused[5]=1;
                pXwon[5]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn5.setText("O");
                btnused[5]=1;
                pOwon[5]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
         if(btnused[8]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn8.setText("X");
                btnused[8]=1;
                pXwon[8]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn8.setText("O");
                btnused[8]=1;
                pOwon[8]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                 if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
         if(btnused[6]==0){ 
            if(turn%2==0)
            {
                turn++;
                btn6.setText("X");
                btnused[6]=1;
                pXwon[6]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
            else
            {
                turn++;
                btn6.setText("O");
                btnused[6]=1;
                pOwon[6]=1;
                
                int result1=pXwon();
                int result2=pOwon();
                
                if(result1==1){
                    JOptionPane.showMessageDialog(rootPane, "X won");
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("X won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    }
                else if(result2==1)
                {
                  JOptionPane.showMessageDialog(rootPane, "O won");
                   
                    PrintWriter out = null;
                    try {
                        out = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\soume\\Documents\\NetBeansProjects\\TicTacToe\\src\\rank.txt", true)));
                            out.println("O won - "+dtf.format(now)+"\n");
                    } catch (IOException e) {
                        System.err.println(e);
                    } finally {
                        if (out != null) {
                            out.close();
                        }
                    } 
                    
                    
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This button was used before!");
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        //
        btn0.setText("");
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        turn=2;
        for(int i=0;i<9;i++)
        {
            btnused[i]=0;
            pXwon[i]=0;
            pOwon[i]=0;
        }
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Menu menu=new Menu();
        this.hide();
        menu.show();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
